More changes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -219,54 +219,75 @@ jobs:
             # exit 1
       # Here's where you will add some code to rollback on failure
 
-run-migrations:
-  docker:
-    - image: cimg/node:15.0.1
-  steps:
-    - checkout
-    - restore_cache:
-        keys: [backend-build]
-    - attach_workspace:
-        at: project/.circleci/ansible
-    - run:
-        name: Run migrations
-        command: |
-          cd backend
-          npm install   
-          npm run migrations > migrations_dump.txt
-          cat migrations_dump.txt
-    - run:
-        name: Send migration status to kvdb.io OR memstash.io
-        command: |
-          if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-          then  
-            echo "Migrations has completed successfully"               
-            curl --insecure https://kvdb.io/NZrFCGtxSFcjgKnJBPWGHY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
-          fi
-        # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-    # - destroy-environment:
-    # Here's where you will add some code to rollback on failure
+  run-migrations:
+    docker:
+      - image: cimg/node:15.0.1
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - attach_workspace:
+          at: project/.circleci/ansible
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install   
+            npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
+      - run:
+          name: Send migration status to kvdb.io OR memstash.io
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then  
+              echo "Migrations has completed successfully"               
+              curl --insecure https://kvdb.io/NZrFCGtxSFcjgKnJBPWGHY/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+          # workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - destroy-environment:
 
-  # deploy-frontend:
-  #   docker:
-  #     # Docker image here that supports AWS CLI
-  #   steps:
-  #     # Checkout code from git
-  #     - run:
-  #         name: Install dependencies
-  #         command: |
-  #           # your code here
-  #     - run:
-  #         name: Get backend url
-  #         command: |
-  #           # your code here
-  #           export API_URL="http://${BACKEND_IP}:3030"
-  #           echo "${API_URL}"
-  #     - run:
-  #         name: Deploy frontend objects
-  #         command: |
-  #           # your code here
-  #     # Here's where you will add some code to rollback on failure
+  deploy-frontend:
+    docker:
+      - image: python:3.7-alpine3.11
+    steps:
+      - checkout
+      # - run: yum install -y tar gzip
+      # - run: install nodejs npm
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update ansible
+            apk add --update gzip
+            apk add --update tar
+            apk add --update nodejs npm
+            pip install awscli
+            # exit 1
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+              --query "Reservations[*].Instances[*].PublicIpAddress" \
+              --filters "Name=tag:project,Values=udapeople-backend" \
+              --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - restore_cache:
+          keys: [frontend-deploy]
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      # - destroy-environment
+      #     # id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Here's where you will add some code to rollback on failure       
 
   # deploy-backend:
   #   docker:
@@ -363,10 +384,10 @@ workflows:
       #     only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
       # - deploy-backend:
       #     requires: [run-migrations]
       # - smoke-test:
